version: '2.1'
services:
  project:
    build: .
    volumes:
        - .:/home/node/app
    ports:
      - "80:8080"
      - "9229:9229"
    command: sh -c "npm start"
    links:
      - pg
  pg:
    image: postgres:12.0
    restart: always
    environment:
         - POSTGRES_DB=test
         - POSTGRES_USER=rayed
         - POSTGRES_PASSWORD=password
    volumes:
      - postgresdata
    ports: 
      - "5432:5432"
    expose:
      - "5432"
  elasticsearch:
    image: elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.5.2
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
  
