version: '2.1'
services:
  project:
    build: .
    volumes:
        - .:/home/node/app
    ports:
      - "80:8080"
      - "9229:9229"
    command: sh -c "npm start"
    links:
      - pg
  pg:
    image: postgres:12.0
    restart: always
    environment:
         - POSTGRES_DB=test
         - POSTGRES_USER=rayed
         - POSTGRES_PASSWORD=password
    volumes:
      - postgresdata
    ports: 
      - "5432:5432"
    expose:
      - "5432"
    
volumes:
  postgresdata:
