version: '2.1'
services:
  project:
    build: .
    volumes:
        - .:/home/node/app
    ports:
      - "80:8080"
      - "9229:9229"
    command: sh -c "npm start"
    links:
      - mongo
  mongo:
    image: mongo:4.2.0-bionic
    volumes:
      - mongodata
    ports: 
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
      - "28017:28017"
    expose:
      - "27017-27019"
volumes:
  mongodata:
